In [8]:
# =========================================================
# Script to calculate the kw_summary table
# (Kruskal–Wallis + epsilon-squared) from CSV
#
# Input: data.csv
# Output:
#    - DataFrame kw_summary
#    - LaTeX block ready to paste into the paper
# =========================================================

import pandas as pd
import numpy as np
from scipy.stats import kruskal

# ---------- Load file ----------
filename = "data.csv"
print("Loading file:", filename)

df = pd.read_csv(filename)
df.columns = [c.strip() for c in df.columns]
print("Columns found:", list(df.columns))
print("Rows:", len(df))

# ---------- Config ----------
# Group columns to test
GROUP_COL_CANDIDATES = ["Group", "MBTI", "GENDER", "Profile"]

# Outcome columns (metrics from CSV)
# REQ = Nota Requisitos
# DEV = Nota Desenvolvimento  
# PROVA = Prova Teórica
# NOTA FINAL = Nota Final
OUTCOME_COLS = ["REQ", "DEV", "PROVA", "NOTA FINAL"]

# ---------- Helpers ----------
def find_first_existing_col(df: pd.DataFrame, candidates: list[str]) -> str:
    for c in candidates:
        if c in df.columns:
            return c
    raise KeyError(
        f"None of the candidate columns were found.\n"
        f"Candidates: {candidates}\n"
        f"Columns in file: {list(df.columns)}"
    )

def to_numeric_series(s: pd.Series) -> pd.Series:
    # converts strings with comma/spaces; forces NaN when not numeric
    s2 = (
        s.astype(str)
         .str.replace("\u00a0", " ", regex=False)  # NBSP
         .str.replace(",", ".", regex=False)
         .str.strip()
    )
    return pd.to_numeric(s2, errors="coerce")

def epsilon_squared_from_H(H: float, k: int, N: int) -> float:
    """
    Epsilon-squared for Kruskal–Wallis:
      eps2 = (H - k + 1) / (N - k)
    Can become negative when H < k-1; we truncate to 0.
    """
    if N <= k:
        return float("nan")
    eps2 = (H - k + 1) / (N - k)
    return float(max(0.0, eps2))

def escape_latex(s: str) -> str:
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    out = str(s)
    for k, v in repl.items():
        out = out.replace(k, v)
    return out

def fmt_p(p: float) -> str:
    if pd.isna(p):
        return "--"
    if p < 0.001:
        return "<0.001"
    return f"{p:.3f}"

def fmt_eps(eps: float) -> str:
    if pd.isna(eps):
        return "--"
    return f"{eps:.3f}"

# ---------- Process each group column ----------
outcome_cols = [c for c in OUTCOME_COLS if c in df.columns]
if not outcome_cols:
    raise KeyError(
        f"No outcome column found.\n"
        f"Expected: {OUTCOME_COLS}\n"
        f"Columns in file: {list(df.columns)}"
    )

print("\nOutcome columns found:", outcome_cols)

# Metric names for display
metric_names = {
    "REQ": "Nota Requisitos",
    "DEV": "Nota Desenvolvimento",
    "PROVA": "Prova Teórica",
    "NOTA FINAL": "Nota Final"
}

for group_col in GROUP_COL_CANDIDATES:
    if group_col not in df.columns:
        print(f"\n[WARNING] Group column '{group_col}' not found. Skipping.")
        continue
    
    print("\n" + "="*80)
    print(f"ANALYSIS BY: {group_col}")
    print("="*80)
    
    # Normalize group column
    df[group_col] = df[group_col].astype(str).str.strip()
    
    rows = []
    for outcome in outcome_cols:
        tmp = df[[group_col, outcome]].copy()
        tmp[outcome] = to_numeric_series(tmp[outcome])

        tmp = tmp.dropna(subset=[outcome])
        tmp = tmp[tmp[group_col].notna() & (tmp[group_col] != "")]

        groups = []
        group_names = []
        for g, sub in tmp.groupby(group_col):
            vals = sub[outcome].to_numpy(dtype=float)
            if len(vals) > 0:
                groups.append(vals)
                group_names.append(g)

        k = len(groups)
        N = int(tmp.shape[0])

        if k < 2:
            H = np.nan
            p = np.nan
            eps2 = np.nan
        else:
            H, p = kruskal(*groups, nan_policy="omit")
            eps2 = epsilon_squared_from_H(H, k, N)

        rows.append(
            {
                "Variable": metric_names.get(outcome, outcome),
                "Groups (k)": k,
                "N": N,
                "H (KW)": float(H) if pd.notna(H) else np.nan,
                "p (KW)": float(p) if pd.notna(p) else np.nan,
                "epsilon^2": float(eps2) if pd.notna(eps2) else np.nan,
                "Groups found": ", ".join(group_names),
            }
        )

    kw_df = pd.DataFrame(rows)

    print(f"\n=== Kruskal–Wallis Summary: {group_col} ===")
    display(kw_df[["Variable", "Groups (k)", "N", "p (KW)", "epsilon^2", "Groups found"]])

    # ---------- Generate LaTeX table ----------
    latex_lines = []
    latex_lines.append(r"\begin{table}[t]")
    latex_lines.append(r"\centering")
    latex_lines.append(r"\small")
    latex_lines.append(f"\\caption{{Inferential results (Kruskal--Wallis) per performance variable, comparing by {group_col}. Reports $p$-value and effect size $\\epsilon^2$ (epsilon-squared).}}")
    latex_lines.append(f"\\label{{tab:kw-{group_col.lower()}}}")
    latex_lines.append(r"\begin{tabular}{lrrrr}")
    latex_lines.append(r"\toprule")
    latex_lines.append(r"\textbf{Variable} & \textbf{Groups (k)} & \textbf{N} & \textbf{$p$ (KW)} & \textbf{$\epsilon^2$} \\")
    latex_lines.append(r"\midrule")

    for _, r in kw_df.iterrows():
        var = escape_latex(r["Variable"])
        k = int(r["Groups (k)"]) if pd.notna(r["Groups (k)"]) else 0
        N = int(r["N"]) if pd.notna(r["N"]) else 0
        p = fmt_p(r["p (KW)"])
        eps = fmt_eps(r["epsilon^2"])
        latex_lines.append(f"{var} & {k} & {N} & {p} & {eps} \\\\")

    latex_lines.append(r"\bottomrule")
    latex_lines.append(r"\end{tabular}")
    latex_lines.append(r"\end{table}")

    latex_table = "\n".join(latex_lines)

    print(f"\n=== LaTeX for {group_col} ===\n")
    print(latex_table)
    print("\n")

print("\n" + "="*80)
print("COMPLETED!")
print("="*80)

Loading file: data.csv
Columns found: ['Turma', 'MBTI', 'YEAR', 'GENDER', 'REQ', 'DEV', 'PROVA', 'NOTA FINAL', 'Group', 'Profile']
Rows: 102

Outcome columns found: ['REQ', 'DEV', 'PROVA', 'NOTA FINAL']

================================================================================
ANALYSIS BY: Group
================================================================================

=== Kruskal–Wallis Summary: Group ===

,Variable,Groups (k),N,p (KW),epsilon^2,Groups found
0,Nota Requisitos,4,102,0.249548,0.011354,"Analistas, Diplomatas, Exploradores, Sentinelas"
1,Nota Desenvolvimento,4,102,0.769247,0.000000,"Analistas, Diplomatas, Exploradores, Sentinelas"
2,Prova Teórica,4,102,0.786363,0.000000,"Analistas, Diplomatas, Exploradores, Sentinelas"
3,Nota Final,4,102,0.619489,0.000000,"Analistas, Diplomatas, Exploradores, Sentinelas"

=== LaTeX for Group ===

\begin{table}[t]
\centering
\small
\caption{Inferential results (Kruskal--Wallis) per performance variable, comparing by Group. Reports $p$-value and effect size $\epsilon^2$ (epsilon-squared).}
\label{tab:kw-group}
\begin{tabular}{lrrrr}
\toprule
\textbf{Variable} & \textbf{Groups (k)} & \textbf{N} & \textbf{$p$ (KW)} & \textbf{$\epsilon^2$} \\
\midrule
Nota Requisitos & 4 & 102 & 0.250 & 0.011 \\
Nota Desenvolvimento & 4 & 102 & 0.769 & 0.000 \\
Prova Teórica & 4 & 102 & 0.786 & 0.000 \\
Nota Final & 4 & 102 & 0.619 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}



================================================================================
ANALYSIS BY: MBTI
================================================================================

=== Kruskal–Wallis Summary: MBTI ===

,Variable,Groups (k),N,p (KW),epsilon^2,Groups found
0,Nota Requisitos,28,102,0.426603,0.009449,"ENFJ-A, ENFJ-T, ENFP-A, ENFP-T, ENTJ-A, ENTJ-T..."
1,Nota Desenvolvimento,28,102,0.713930,0.000000,"ENFJ-A, ENFJ-T, ENFP-A, ENFP-T, ENTJ-A, ENTJ-T..."
2,Prova Teórica,28,102,0.737069,0.000000,"ENFJ-A, ENFJ-T, ENFP-A, ENFP-T, ENTJ-A, ENTJ-T..."
3,Nota Final,28,102,0.654401,0.000000,"ENFJ-A, ENFJ-T, ENFP-A, ENFP-T, ENTJ-A, ENTJ-T..."

=== LaTeX for MBTI ===

\begin{table}[t]
\centering
\small
\caption{Inferential results (Kruskal--Wallis) per performance variable, comparing by MBTI. Reports $p$-value and effect size $\epsilon^2$ (epsilon-squared).}
\label{tab:kw-mbti}
\begin{tabular}{lrrrr}
\toprule
\textbf{Variable} & \textbf{Groups (k)} & \textbf{N} & \textbf{$p$ (KW)} & \textbf{$\epsilon^2$} \\
\midrule
Nota Requisitos & 28 & 102 & 0.427 & 0.009 \\
Nota Desenvolvimento & 28 & 102 & 0.714 & 0.000 \\
Prova Teórica & 28 & 102 & 0.737 & 0.000 \\
Nota Final & 28 & 102 & 0.654 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}



================================================================================
ANALYSIS BY: GENDER
================================================================================

=== Kruskal–Wallis Summary: GENDER ===

               Variable  Groups (k)    N    p (KW)  epsilon^2 Groups found
0       Nota Requisitos           2  102  0.109894   0.015557         F, M
1  Nota Desenvolvimento           2  102  0.002205   0.083702         F, M
2         Prova Teórica           2  102  0.086901   0.019309         F, M
3            Nota Final           2  102  0.003577   0.074868         F, M

=== LaTeX for GENDER ===

\begin{table}[t]
\centering
\small
\caption{Inferential results (Kruskal--Wallis) per performance variable, comparing by GENDER. Reports $p$-value and effect size $\epsilon^2$ (epsilon-squared).}
\label{tab:kw-gender}
\begin{tabular}{lrrrr}
\toprule
\textbf{Variable} & \textbf{Groups (k)} & \textbf{N} & \textbf{$p$ (KW)} & \textbf{$\epsilon^2$} \\
\midrule
Nota Requisitos & 2 & 102 & 0.110 & 0.016 \\
Nota Desenvolvimento & 2 & 102 & 0.002 & 0.084 \\
Prova Teórica & 2 & 102 & 0.087 & 0.019 \\
Nota Final & 2 & 102 & 0.004 & 0.075 \\
\bottomrule
\end{tabular}
\end{table}



================================================================================
ANALYSIS BY: Profile
================================================================================

=== Kruskal–Wallis Summary: Profile ===

,Variable,Groups (k),N,p (KW),epsilon^2,Groups found
0,Nota Requisitos,15,102,0.781701,0.0,"Apoiador, Arquiteto, Ativista, Aventureiro, Co..."
1,Nota Desenvolvimento,15,102,0.995969,0.0,"Apoiador, Arquiteto, Ativista, Aventureiro, Co..."
2,Prova Teórica,15,102,0.707931,0.0,"Apoiador, Arquiteto, Ativista, Aventureiro, Co..."
3,Nota Final,15,102,0.981028,0.0,"Apoiador, Arquiteto, Ativista, Aventureiro, Co..."

=== LaTeX for Profile ===

\begin{table}[t]
\centering
\small
\caption{Inferential results (Kruskal--Wallis) per performance variable, comparing by Profile. Reports $p$-value and effect size $\epsilon^2$ (epsilon-squared).}
\label{tab:kw-profile}
\begin{tabular}{lrrrr}
\toprule
\textbf{Variable} & \textbf{Groups (k)} & \textbf{N} & \textbf{$p$ (KW)} & \textbf{$\epsilon^2$} \\
\midrule
Nota Requisitos & 15 & 102 & 0.782 & 0.000 \\
Nota Desenvolvimento & 15 & 102 & 0.996 & 0.000 \\
Prova Teórica & 15 & 102 & 0.708 & 0.000 \\
Nota Final & 15 & 102 & 0.981 & 0.000 \\
\bottomrule
\end{tabular}
\end{table}



================================================================================
COMPLETED!
================================================================================